Error Still  Proceeds On Doors all over toontown :(
File "toontown\building\DistributedToonInterior.py", line 116, in setup
DNADoor.setupDoor(doorNP, self.interior, door_origin, self.dnaStore,
str(self.block), color)
TypeError: an integer is required